sudo: false
language: go
# https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance
go:
  - 1.x
  - tip
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script:
  - go get -v github.com/mattn/goveralls
  - go get -v github.com/go-playground/overalls
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - overalls -project github.com/nochso/colourl -covermode atomic -- -race -v
  - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci
