language: go
sudo: false
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=css.coverprofile ./css
  - go test -coverprofile=page.coverprofile ./page
  - go test -coverprofile=palette.coverprofile ./palette
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci
